name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: echo `date`
    - name: Set env
      run: echo "VERSION=$(git describe --exact-match HEAD || echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: env
      run: echo "ver=$(git remote show origin)"
    - name: validating
      run: echo $VERSION && echo $ver
