name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: echo `date`
    - name: Set env
      run: echo "VERSION=$(git describe --exact-match HEAD || echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
    - name: env
      run: echo ${GITHUB_REPOSITORY##*/}
    - name: buid id
      run: echo ${{ github.run_number }}
    - name: validating
      run: echo $VERSION 
    - name: file
      run: echo ${{ secrets.file }} 
  
